class SecretsController < ApplicationController

    #skip the check for the autenticty token, which is usually generated by the formwith token
    #we are submitting our form from the React front end, so we do not have this token
    skip_before_action :verify_authenticity_token, raise: false

    def index

        # Deal with CORS header checking for Ajax reqwuest by defining a response header
        # that states than any (*) requests are allowed to make
        # AJAX requests
        # headers['Access-Control-Allow-Origin'] = '*'
        # we covered thiss by installing a gem (rack-cors) and then adding a file in initialization: 

        render json: Secret.all #send to the AJAX jscode, as json, an array of Secret objects.
        #This allows the front end to make an ajax request to access this information

    end #end index

    def create
        
        secret = Secret.create content: params[:content]
        if secret.persisted? 
            render json: secret #send the created secret object as JSON response
        else
            render json: { error: 'Could not create secret' }, status: 422 #'Unprocessable Entity'
        end #end if

    end  #end create


end
